spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      metrics:
        enabled: true   # default value (see /actuator/metrics/spring.cloud.gateway.requests and /actuator/metrics/spring.cloud.gateway.routes.count)
      actuator:
        verbose:
          enabled: true   # see /actuator/gateway/routes

management:
  endpoint:
    gateway:
      enabled: true       # default value
  endpoints:
    web:
      exposure:
        include: "*"        # OR include: gateway
  health:
    redis:
      enabled: true
